"""update tables3

Revision ID: 06c2e846bae8
Revises: 287383f845ab
Create Date: 2022-09-03 21:29:35.262938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c2e846bae8'
down_revision = '287383f845ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
