"""update_tables9

Revision ID: 195f526a34f1
Revises: 8d1e8405e477
Create Date: 2022-09-06 17:21:07.004731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195f526a34f1'
down_revision = '8d1e8405e477'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
