"""update tables2

Revision ID: 287383f845ab
Revises: a58adf20e620
Create Date: 2022-09-03 20:27:23.839441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287383f845ab'
down_revision = 'a58adf20e620'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
