"""update_tables11

Revision ID: 462ba827ce1d
Revises: e1da597ac42c
Create Date: 2022-09-06 17:35:05.070188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462ba827ce1d'
down_revision = 'e1da597ac42c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
