"""update_tables7

Revision ID: 5482aa1cf6aa
Revises: fbe46c25fd70
Create Date: 2022-09-06 17:16:22.656286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5482aa1cf6aa'
down_revision = 'fbe46c25fd70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
