"""update_tables8

Revision ID: 8d1e8405e477
Revises: 5482aa1cf6aa
Create Date: 2022-09-06 17:18:36.856390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1e8405e477'
down_revision = '5482aa1cf6aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
