"""update_tables10

Revision ID: e1da597ac42c
Revises: 195f526a34f1
Create Date: 2022-09-06 17:34:22.938480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1da597ac42c'
down_revision = '195f526a34f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('last_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'last_name')
    # ### end Alembic commands ###
