"""update_tables5

Revision ID: f725a3cecc46
Revises: 2d80e562a82b
Create Date: 2022-09-05 21:15:12.853086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f725a3cecc46'
down_revision = '2d80e562a82b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('object', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'object')
    # ### end Alembic commands ###
