"""update_tables6

Revision ID: fbe46c25fd70
Revises: f725a3cecc46
Create Date: 2022-09-05 21:49:20.135606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe46c25fd70'
down_revision = 'f725a3cecc46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'object')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('object', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
