"""
Словник з розширеннями, при додаванні нового розширення
 - будуть створюватись нові теки під файли з новими розширеннями
"""

REGISTER_EXTENSIONS = {
    "JPEG": "images",
    "JPG": "images",
    "PNG": "images",
    "SVG": "images",
    "GIF": "images",
    "MP3": "audio",
    "OGG": "audio",
    "WAV": "audio",
    "AMR": "audio",
    "MP4": "video",
    "AVI": "video",
    "MOV": "video",
    "MKV": "video",
    "DOC": "document",
    "DOCX": "document",
    "TXT": "document",
    "PDF": "document",
    "XLSX": "document",
    "XLS": "document",
    "CSV": "document",
    "PPTX": "document",
    "ZIP": "archives",
    "GZ": "archives",
    "TAR": "archives",
    "RAR": "archives",
    "ARJ": "archives",
    "APP": "programs",
    "PY": "programs",
    "HTML": "programs",
    "BIN": "programs",
    "DAT": "programs",
    "JSON": "programs",
    "XLM": "programs",
    "PKG": "programs",
    "JS": "programs",
    "YML": "programs",
    "YAML": "programs",
    "MD": "programs",
    "": "other",
}
