version: "3.9"

services:
  web:
    container_name: web-${APP_NAME}
    hostname: web-${APP_NAME}
    restart: always
    image: web-${APP_NAME}
    ports:
      - "5440:5440"

    environment:
      - ./.env
#    depends_on:
#      db:
#        condition: service_healthy
    build:
      dockerfile: Dockerfile
      context: .

  nginx:
    image: nginx:1.19-alpine
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf